---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapp-container
          image: priti/minijava:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapp-service
spec:
  type: LoadBalancer
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
