---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: java_pipeline/Dockerfile

    - name: Copy Artifact (.war file)
      copy:
        src: target/maven-web-app.war
        dest: /home/ansadmin/

    - name: Build Docker image
      command: docker build -t priti/minijava .

    - name: Push Docker image to Docker Hub
      command: docker push priti/minijava .

- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
    - name: Copy K8s deployment file
      copy:
        src: k8s-deploy.yml
        dest: java_pipeline/k8s-deploy.yml


    - name: Deploy to Kubernetes
      command: kubectl apply -f java_pipeline
/docker-k8s-jenkinsfile

